[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/contracts"
]

eth_rpc_url = "localhost:8545"

[fuzz]
runs = 8192
max_test_rejects = 256000

[profile.production]
src = "src"
out = "out"
libs = ["lib"]

optimizer = true
optimizer_runs = 100000000
